#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

GREEN='\033[0;32m'
print_success() {
  printf "${GREEN}RUNNING VALIDATIONS BEFORE COMMITTING $1${NC}\n"
}
print_success_lines() {
  printf "${GREEN}================================= $1${NC}\n"
}

print_success_lines
print_success 
print_success_lines
npx lint-staged
